# Generated by Django 5.1.4 on 2026-02-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_alter_books_id_alter_readers_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='readers',
            name='image',
            field=models.ImageField(default=True, upload_to='uploads/images/'),
        ),
    ]
