# Generated by Django 5.1.4 on 2026-02-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_readers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
    ]
